Import task definition if not provided

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -23,15 +23,23 @@ target_group=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_GROUP:-""}
 load_balancer_name=${BUILDKITE_PLUGIN_ECS_DEPLOY_LOAD_BALANCER_NAME:-""}
 target_container=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_CONTAINER_NAME:-""}
 target_port=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_CONTAINER_PORT:-""}
+task_definition=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_DEFINITION:-""}
 
-if [ -z "${BUILDKITE_PLUGIN_ECS_DEPLOY_CONTAINER_DEFINITIONS:-}" ]; then
-  container_definitions=$(mktemp)
-  if ! aws ecs describe-task-definition --task-definition "${task_family}" --query 'taskDefinition.containerDefinitions' >"${container_definitions}"; then
-    echo ":boom: Could not get container definitions"
+if [ -z "${task_definition}" ]; then
+  task_file=$(mktemp)
+  if ! aws ecs describe-task-definition --task-definition "${task_family}" --query 'taskDefinition' >"${task_file}"; then
+    echo ":boom: Could not get task definitions (you need to define one in your repository and use the task-definition option)"
     exit 1
   fi
-  container_definitions_json=$(cat "${container_definitions}")
-  rm "${container_definitions}"
+
+  task_definition_json=$(cat "${task_file}")
+  rm "${task_file}"
+else
+  task_definition_json=$(cat "${task_definition}")
+fi
+
+if [ -z "${BUILDKITE_PLUGIN_ECS_DEPLOY_CONTAINER_DEFINITIONS:-}" ]; then
+  container_definitions_json=$(jq '.containerDefinitions' <"${task_definition_json}")
 else
   container_definitions_json=$(cat "${BUILDKITE_PLUGIN_ECS_DEPLOY_CONTAINER_DEFINITIONS}")
 fi
@@ -99,9 +107,7 @@ if [[ -n "${execution_role}" ]]; then
     register_command+=(--execution-role-arn "${execution_role}")
 fi
 
-task_definition=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_DEFINITION:-""}
 if [[ -n "${task_definition}" ]]; then
-    task_definition_json=$(cat "${task_definition}")
     register_command+=(--cli-input-json "${task_definition_json}")
 fi
 
