Add support for ELBv1

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -9,10 +9,13 @@ task_definition=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_DEFINITION?}
 desired_count=${BUILDKITE_PLUGIN_ECS_DEPLOY_DESIRED_COUNT:-"1"}
 task_role_arn=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_ROLE_ARN:-""}
 target_group=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_GROUP:-""}
-# Resolve any runtime environment variables it has
-target_group=$(eval "echo $target_group")
+load_balancer_name=${BUILDKITE_PLUGIN_ECS_DEPLOY_LOAD_BALANCER_NAME:-""}
 target_container=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_CONTAINER_NAME:-""}
 target_port=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_CONTAINER_PORT:-""}
+
+# Resolve any runtime environment variables it has
+target_group=$(eval "echo $target_group")
+load_balancer_name=$(eval "echo $load_balancer_name")
 
 function create_service() {
     local cluster_name=$1
@@ -34,8 +37,19 @@ function generate_target_group_arguments() {
     local target_container=$2
     local target_port=$3
     local target_group_arguments=""
-    if [[ -n $target_group ]] && [[ -n $target_container ]] && [[ -n $target_port ]]; then
-      target_group_arguments="--load-balancers targetGroupArn=${target_group},containerName=${target_container},containerPort=${target_port}"
+    if [[ -n $target_container ]] && [[ -n $target_port ]]; then
+      local load_balancer_ref=""
+      if [[ -n $target_group ]]; then
+        load_balancer_ref="targetGroupArn=${target_group}"
+      elif [[ -n $load_balancer_name ]]; then
+        load_balancer_ref="loadBalancerName=${load_balancer_name}"
+      else
+        echo "+++ ^^^"
+        echo "+++ You must specify either `target-group` or `load-balancer-name`"
+        exit 1
+      fi
+
+      target_group_arguments="--load-balancers ${load_balancer_ref},containerName=${target_container},containerPort=${target_port}"
     fi
     echo "$target_group_arguments"
 }
@@ -74,10 +88,11 @@ echo "Registered ${task_family}:${task_revision}"
 create_service "$cluster" "${task_family}:${task_revision}" "$service_name" "$desired_count" "$target_group" "$target_container" "$target_port"
 
 lb_config=$(aws ecs describe-services --cluster "$cluster" --services "$service_name" --query 'services[?status==`ACTIVE`]' |jq -r '.[0].loadBalancers[0]')
-error="+++ Cannot update a service to add a load balancer. First delete the service and then run again, or rename the service to force a new one to be created"
+error="+++ ^^^
++++ Cannot update a service to add/remove a load balancer. First delete the service and then run again, or rename the service to force a new one to be created"
 
 # No easy way to tell if the target group has changed, since describe-services only returns the load balancer name
-if [[ "$lb_config" == "null" ]] && [[ -n $target_group ]]; then
+if [[ "$lb_config" == "null" ]] && [ -n "$target_group" -o -n "$load_balancer_name" ]; then
   echo "$error"
   exit 1
 fi
@@ -86,6 +101,12 @@ if [[ "$lb_config" == "null" ]]; then
   # noop
   true
 elif [[ $(echo "$lb_config" |jq -r '.containerName') != "$target_container" ]] || [[ $(echo "$lb_config" |jq -r '.containerPort') -ne $target_port ]]; then
+  echo "$error"
+  exit 1
+elif [[ -n "$target_group" ]] && [[ $(echo "$lb_config" |jq -r '.targetGroupArn') != "$target_group" ]]; then
+  echo "$error"
+  exit 1
+elif [[ -n "$load_balancer_name" ]] && [[ $(echo "$lb_config" |jq -r '.loadBalancerName') != "$load_balancer_name" ]]; then
   echo "$error"
   exit 1
 fi
