Add support for ALBs

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -8,18 +8,34 @@ image=${BUILDKITE_PLUGIN_ECS_DEPLOY_IMAGE?}
 task_definition=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_DEFINITION?}
 desired_count=${BUILDKITE_PLUGIN_ECS_DEPLOY_DESIRED_COUNT:-"1"}
 task_role_arn=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_ROLE_ARN:-""}
+target_group=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_GROUP:-""}
+target_container=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_CONTAINER_NAME:-""}
+target_port=${BUILDKITE_PLUGIN_ECS_DEPLOY_TARGET_CONTAINER_PORT:-""}
 
 function create_service() {
     local cluster_name=$1
     local task_definition=$2
     local service_name=$3
     local desired_count=$4
+    local target_group_arguments
+    target_group_arguments=$(generate_target_group_arguments "$5" "$6" "$7")
 
     service_defined=$(aws ecs describe-services --cluster "$cluster_name" --service "$service_name" --query 'services[*].status' --output text |wc -l)
     if [[ $service_defined -eq 0 ]]; then
         echo "--- :ecs: Creating a Service $service_name in cluster $cluster_name"
-        aws ecs create-service --cluster "$cluster_name" --service-name "$service_name" --task-definition "$task_definition" --desired-count "$desired_count"
+        aws ecs create-service --cluster "$cluster_name" --service-name "$service_name" --task-definition "$task_definition" --desired-count "$desired_count" $target_group_arguments
     fi
+}
+
+function generate_target_group_arguments() {
+    local target_group=$1
+    local target_container=$2
+    local target_port=$3
+    local target_group_arguments=""
+    if [[ -n $target_group ]] && [[ -n $target_container ]] && [[ -n $target_port ]]; then
+      target_group_arguments="--load-balancers 'targetGroupArn=${target_group},containerName=${target_container},containerPort=${target_port}'"
+    fi
+    echo "$target_group_arguments"
 }
 
 ## This is the template definition of your containers
@@ -53,7 +69,22 @@ task_revision=$(jq '.taskDefinition.revision' <<< "$json_output")
 echo "Registered ${task_family}:${task_revision}"
 
 # Create service if it doesn't already exist
-create_service "$cluster" "${task_family}:${task_revision}" "$service_name" "$desired_count"
+create_service "$cluster" "${task_family}:${task_revision}" "$service_name" "$desired_count" "$target_group" "$target_container" "$target_port"
+
+lb_config=$(aws ecs describe-services --cluster "$cluster" --services "$service_name" --query 'services[0].{loadBalancers:loadBalancers}' |jq -r '.loadBalancers[0]')
+error="+++ Cannot update a service to add a load balancer. First delete the service and then run again, or rename the service to force a new one to be created"
+
+# No easy way to tell if the target group has changed, since describe-services only returns the load balancer name
+if [[ "$lb_config" == "null" ]]; then
+  # do nothing
+  true
+elif [[ "$lb_config" == "null" ]] && [[ -z $target_group ]]; then
+  echo "$error"
+  exit 1
+elif [[ $(echo "$lb_config" |jq -r '.containerName') != $target_container ]] || [[ $(echo "$lb_config" |jq -r '.containerPort') -ne $target_port ]]; then
+  echo "$error"
+  exit 1
+fi
 
 echo "--- :ecs: Updating service for ${service_name}"
 aws ecs update-service \
